fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: tobias.olry@gmail.com
        sender_name: Tobias Olry
    service:
        mailer: mailer

