security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        'FOS\UserBundle\Model\UserInterface': sha512

    firewalls:
        main:
            remember_me:
                secret: '%kernel.secret%'
                name: 'mental-note'
                lifetime: 604800
                path: /
                always_remember_me: true
            pattern: ^/
            form_login:
                provider: fos_userbundle
                #csrf_provider: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_REMEMBERED }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


