services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/

  memcached:
    image: memcached:latest
    links:
      - php

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: test
    links:
      - php
    profiles:
      - development
